name: ci

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - { name: avr, tag: darkautism/arduino-toolchain:avr }
          - { name: esp8266, tag: darkautism/arduino-toolchain:esp8266 }
          - { name: esp32, tag: darkautism/arduino-toolchain:esp32 }
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERTOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          build-args: |
            PLATFORM=${{ matrix.platform.name }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ matrix.platform.tag }}